export enum SetWeightState {
    SET_WEIGHTS = 'SET_WEIGHTS',
    REMOVE_WEIGHT = 'REMOVE_WEIGHT',
    UPDATE_WEIGHT = 'UPDATE_WEIGHT',
    ADD_WEIGHT = 'ADD_WEIGHT',
    SET_NOTIFICATION = "SET_NOTIFICATION"
};

export enum SetExerciseState {
    SET_MUSCLES = 'SET_MUSCLES',
    SET_CATEGORIES = 'SET_EQUIPMENT',
    SET_EQUIPMENT = 'SET_EQUIPMENT',
};
