// This code is autogenerated in the backend repo in extract-i18n.py do not edit!

// Translate dynamic strings that are returned from the server
// These strings such as categories or equipment are returned by the server
// in English and need to be translated here in the application (there are
// probably better ways to do this, but that's the way it is right now).

import { useTranslation } from "react-i18next";

// eslint-disable-next-line @typescript-eslint/no-unused-vars
const DummyComponent = () => {
    const [t] = useTranslation();
    t("server.abs");
    t("server.arms");
    t("server.back");
    t("server.barbell");
    t("server.bench");
    t("server.biceps");
    t("server.body_weight");
    t("server.calves");
    t("server.cardio");
    t("server.chest");
    t("server.dumbbell");
    t("server.glutes");
    t("server.gym_mat");
    t("server.hamstrings");
    t("server.incline_bench");
    t("server.kettlebell");
    t("server.kilometers");
    t("server.kilometers_per_hour");
    t("server.lats");
    t("server.legs");
    t("server.miles");
    t("server.miles_per_hour");
    t("server.minutes");
    t("server.plates");
    t("server.pull_up_bar");
    t("server.quads");
    t("server.repetitions");
    t("server.sz_bar");
    t("server.seconds");
    t("server.shoulders");
    t("server.swiss_ball");
    t("server.triceps");
    t("server.until_failure");
    t("server.kg");
    t("server.lb");
    t("server.none__bodyweight_exercise_");

    return (<p></p>);
};